[sssd]
domains = azuread
config_file_version = 2
services = nss, pam

[domain/azuread]
id_provider = proxy
proxy_lib_name = sss_azuread
fallback_homedir = /home/%u
default_shell = /bin/bash
enumerate = false
cache_credentials = true