[sssd]
domains = azuread
config_file_version = 2
services = nss, pam

[domain/azuread]
id_provider = proxy
proxy_lib_name = sss_azuread
azuread_tenant_id = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
azuread_app_id = yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
cache_credentials = true
ldap_sudo_search_base = ou=Sudoers,dc=yourdomain,dc=com
fallback_homedir = /home/%u
default_shell = /bin/bash
enumerate = false
offline_credentials_expiration = 30